export interface Game{
    id:string,
    title:string,
    thumbnail:string,
    short_description:string,
    game_url:string,
    genres:Array<string>,
    platforms:Array<string>,
    publishers:Array<string>,
    developers:Array<string>,
    release_date:string,
    freetogame_profile_url:string,
    currentList?:string,
    store:Array<any>,
}